- name: Ensure nginx conf directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Copy index.php
  ansible.builtin.template:
    src: index.php.j2
    dest: "/var/www/html/index.php"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart php-fpm
