- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Restart php-fpm
  ansible.builtin.service:
    name: php8.2-fpm
    state: restarted
  become: true
